version: '3'

services:
  mysql_master:
    image: mysql:8.0
    mem_limit: 512m
    mem_reservation: 128M
    env_file:
      - ./master/mysql_master.env
    container_name: mysql_master
    restart: no
    ports:
      - 4406:3306
    volumes:
      - ./master/conf/mysql.conf.cnf:/etc/mysql/my.cnf
      - mysql-master-data:/var/lib/mysql
    networks:
      - mysql-replication-network
  mysql_slave1:
    image: mysql:8.0
    mem_limit: 512m
    mem_reservation: 128M
    env_file:
      - ./slave1/mysql_slave.env
    container_name: mysql_slave1
    restart: no
    ports:
      - 4407:3306
    depends_on:
      - mysql_master
    volumes:
      - ./slave1/conf/mysql.conf.cnf:/etc/mysql/my.cnf
      - mysql-slave1-data:/var/lib/mysql
    networks:
      - mysql-replication-network
  mysql_slave2:
    image: mysql:8.0
    mem_limit: 512m
    mem_reservation: 128M
    env_file:
      - ./slave2/mysql_slave.env
    container_name: mysql_slave2
    restart: no
    ports:
      - 4408:3306
    depends_on:
      - mysql_master
    volumes:
      - ./slave2/conf/mysql.conf.cnf:/etc/mysql/my.cnf
      - mysql-slave2-data:/var/lib/mysql
    networks:
      - mysql-replication-network

volumes:
  mysql-master-data:
    driver: local
  mysql-slave1-data:
    driver: local
  mysql-slave2-data:
    driver: local

networks:
  mysql-replication-network:
    driver: bridge
